export TMUX_POWERLINE_PATCHED_FONT_IN_USE="true"
export TMUX_POWERLINE_THEME="mine"
export TMUX_POWERLINE_STATUS_VISIBILITY="on"
export TMUX_POWERLINE_STATUS_INTERVAL="1"
export TMUX_POWERLINE_STATUS_JUSTIFICATION="centre"

export TMUX_POWERLINE_STATUS_LEFT_LENGTH="420"
export TMUX_POWERLINE_STATUS_RIGHT_LENGTH="680"

export TMUX_POWERLINE_SEG_BATTERY_TYPE="cute"
export TMUX_POWERLINE_SEG_BATTERY_NUM_HEARTS="5"

export TMUX_POWERLINE_SEG_DATE_FORMAT="%d.%m.%Y"
export TMUX_POWERLINE_SEG_DISK_USAGE_FILESYSTEM="/"

export TMUX_POWERLINE_SEG_HOSTNAME_FORMAT="short"

export TMUX_POWERLINE_SEG_NOW_PLAYING_LASTFM_UPDATE_PERIOD="30"
export TMUX_POWERLINE_SEG_NOW_PLAYING_NOTE_CHAR="♫"
export TMUX_POWERLINE_SEG_PWD_MAX_LEN="40"

export TMUX_POWERLINE_SEG_TIME_FORMAT="%H:%M"

export TMUX_POWERLINE_SEG_TMUX_SESSION_INFO_FORMAT="#S:#I.#P"
export TMUX_POWERLINE_SEG_VCS_BRANCH_MAX_LEN="42"
